/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DfdfdsfService } from "../dfdfdsf.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DfdfdsfCreateInput } from "./DfdfdsfCreateInput";
import { Dfdfdsf } from "./Dfdfdsf";
import { DfdfdsfFindManyArgs } from "./DfdfdsfFindManyArgs";
import { DfdfdsfWhereUniqueInput } from "./DfdfdsfWhereUniqueInput";
import { DfdfdsfUpdateInput } from "./DfdfdsfUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DfdfdsfControllerBase {
  constructor(
    protected readonly service: DfdfdsfService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Dfdfdsf })
  @nestAccessControl.UseRoles({
    resource: "Dfdfdsf",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDfdfdsf(
    @common.Body() data: DfdfdsfCreateInput
  ): Promise<Dfdfdsf> {
    return await this.service.createDfdfdsf({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Dfdfdsf] })
  @ApiNestedQuery(DfdfdsfFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Dfdfdsf",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dfdfdsfs(@common.Req() request: Request): Promise<Dfdfdsf[]> {
    const args = plainToClass(DfdfdsfFindManyArgs, request.query);
    return this.service.dfdfdsfs({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Dfdfdsf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Dfdfdsf",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dfdfdsf(
    @common.Param() params: DfdfdsfWhereUniqueInput
  ): Promise<Dfdfdsf | null> {
    const result = await this.service.dfdfdsf({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Dfdfdsf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Dfdfdsf",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDfdfdsf(
    @common.Param() params: DfdfdsfWhereUniqueInput,
    @common.Body() data: DfdfdsfUpdateInput
  ): Promise<Dfdfdsf | null> {
    try {
      return await this.service.updateDfdfdsf({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Dfdfdsf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Dfdfdsf",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDfdfdsf(
    @common.Param() params: DfdfdsfWhereUniqueInput
  ): Promise<Dfdfdsf | null> {
    try {
      return await this.service.deleteDfdfdsf({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
