/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Dfdfdsf } from "./Dfdfdsf";
import { DfdfdsfCountArgs } from "./DfdfdsfCountArgs";
import { DfdfdsfFindManyArgs } from "./DfdfdsfFindManyArgs";
import { DfdfdsfFindUniqueArgs } from "./DfdfdsfFindUniqueArgs";
import { DeleteDfdfdsfArgs } from "./DeleteDfdfdsfArgs";
import { DfdfdsfService } from "../dfdfdsf.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Dfdfdsf)
export class DfdfdsfResolverBase {
  constructor(
    protected readonly service: DfdfdsfService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Dfdfdsf",
    action: "read",
    possession: "any",
  })
  async _dfdfdsfsMeta(
    @graphql.Args() args: DfdfdsfCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Dfdfdsf])
  @nestAccessControl.UseRoles({
    resource: "Dfdfdsf",
    action: "read",
    possession: "any",
  })
  async dfdfdsfs(
    @graphql.Args() args: DfdfdsfFindManyArgs
  ): Promise<Dfdfdsf[]> {
    return this.service.dfdfdsfs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Dfdfdsf, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Dfdfdsf",
    action: "read",
    possession: "own",
  })
  async dfdfdsf(
    @graphql.Args() args: DfdfdsfFindUniqueArgs
  ): Promise<Dfdfdsf | null> {
    const result = await this.service.dfdfdsf(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Dfdfdsf)
  @nestAccessControl.UseRoles({
    resource: "Dfdfdsf",
    action: "delete",
    possession: "any",
  })
  async deleteDfdfdsf(
    @graphql.Args() args: DeleteDfdfdsfArgs
  ): Promise<Dfdfdsf | null> {
    try {
      return await this.service.deleteDfdfdsf(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
