/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PluralNameTestService } from "../pluralNameTest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PluralNameTestCreateInput } from "./PluralNameTestCreateInput";
import { PluralNameTestWhereInput } from "./PluralNameTestWhereInput";
import { PluralNameTestWhereUniqueInput } from "./PluralNameTestWhereUniqueInput";
import { PluralNameTestFindManyArgs } from "./PluralNameTestFindManyArgs";
import { PluralNameTestUpdateInput } from "./PluralNameTestUpdateInput";
import { PluralNameTest } from "./PluralNameTest";
import { TestDatumFindManyArgs } from "../../testDatum/base/TestDatumFindManyArgs";
import { TestDatum } from "../../testDatum/base/TestDatum";
import { TestDatumWhereUniqueInput } from "../../testDatum/base/TestDatumWhereUniqueInput";
import { TransactionMetaDatumFindManyArgs } from "../../transactionMetaDatum/base/TransactionMetaDatumFindManyArgs";
import { TransactionMetaDatum } from "../../transactionMetaDatum/base/TransactionMetaDatum";
import { TransactionMetaDatumWhereUniqueInput } from "../../transactionMetaDatum/base/TransactionMetaDatumWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PluralNameTestControllerBase {
  constructor(
    protected readonly service: PluralNameTestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PluralNameTest })
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: PluralNameTestCreateInput
  ): Promise<PluralNameTest> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        myEventData: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PluralNameTest] })
  @ApiNestedQuery(PluralNameTestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<PluralNameTest[]> {
    const args = plainToClass(PluralNameTestFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        myEventData: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PluralNameTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: PluralNameTestWhereUniqueInput
  ): Promise<PluralNameTest | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        myEventData: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PluralNameTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: PluralNameTestWhereUniqueInput,
    @common.Body() data: PluralNameTestUpdateInput
  ): Promise<PluralNameTest | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          myEventData: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PluralNameTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: PluralNameTestWhereUniqueInput
  ): Promise<PluralNameTest | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          myEventData: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/testData")
  @ApiNestedQuery(TestDatumFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TestDatum",
    action: "read",
    possession: "any",
  })
  async findManyTestData(
    @common.Req() request: Request,
    @common.Param() params: PluralNameTestWhereUniqueInput
  ): Promise<TestDatum[]> {
    const query = plainToClass(TestDatumFindManyArgs, request.query);
    const results = await this.service.findTestData(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        pluralNameTest: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/testData")
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "update",
    possession: "any",
  })
  async connectTestData(
    @common.Param() params: PluralNameTestWhereUniqueInput,
    @common.Body() body: TestDatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      testData: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/testData")
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "update",
    possession: "any",
  })
  async updateTestData(
    @common.Param() params: PluralNameTestWhereUniqueInput,
    @common.Body() body: TestDatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      testData: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/testData")
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "update",
    possession: "any",
  })
  async disconnectTestData(
    @common.Param() params: PluralNameTestWhereUniqueInput,
    @common.Body() body: TestDatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      testData: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/transactionMetaData")
  @ApiNestedQuery(TransactionMetaDatumFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TransactionMetaDatum",
    action: "read",
    possession: "any",
  })
  async findManyTransactionMetaData(
    @common.Req() request: Request,
    @common.Param() params: PluralNameTestWhereUniqueInput
  ): Promise<TransactionMetaDatum[]> {
    const query = plainToClass(TransactionMetaDatumFindManyArgs, request.query);
    const results = await this.service.findTransactionMetaData(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        pluralNameTest: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactionMetaData")
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "update",
    possession: "any",
  })
  async connectTransactionMetaData(
    @common.Param() params: PluralNameTestWhereUniqueInput,
    @common.Body() body: TransactionMetaDatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactionMetaData: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactionMetaData")
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "update",
    possession: "any",
  })
  async updateTransactionMetaData(
    @common.Param() params: PluralNameTestWhereUniqueInput,
    @common.Body() body: TransactionMetaDatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactionMetaData: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactionMetaData")
  @nestAccessControl.UseRoles({
    resource: "PluralNameTest",
    action: "update",
    possession: "any",
  })
  async disconnectTransactionMetaData(
    @common.Param() params: PluralNameTestWhereUniqueInput,
    @common.Body() body: TransactionMetaDatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactionMetaData: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
